spring:
  application:
    name: ChatApplication
  data:
    mongodb:
      database: chatApplication
      host: localhost
      port: 27017
security:
  jwt:
    security-key: 4bbf5ef641e95aa5474f6f9e000b80e83e7c2e441cff743658aafd16a08234c6
    expiration-date: 3600000

