spring:
  application:
    name: ChatApplication
  datasource:
    url: jdbc:mysql://localhost:3306/chatApplication
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: ashum

  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
         dialect: org.hibernate.dialect.MySQL8Dialect
